In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'C:\\Users\\pmgho\\Downloads\\Prajwal Machine Learning Data Set\\python'

In [4]:
os.chdir('C:\\Users\\pmgho\\Downloads\\Prajwal Machine Learning Data Set\\')

In [5]:
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
import seaborn as sns

In [10]:
tips=sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
prajwal_data=sns.load_dataset('flights')
prajwal_data

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [12]:
prajwal_dataset2=sns.load_dataset('iris')
prajwal_dataset2

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
!pip install pandas-profiling

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas-profiling in c:\users\pmgho\appdata\roaming\python\python312\site-packages (3.2.0)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Using cached joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (2.2.3)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (3.10.0)
Requirement already satisfied: pydantic>=1.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (2.8.2)
Requirement already satisfied: PyYAML>=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (6.0.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (3.1.4)
Requirement already satisfied: markupsafe~=2.1.1 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (2.1.3)
Requirement already satisfied: visions==0.7.4 in c:\programdata\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (1.26.4)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (0.5.2)
Requirement already satisfied: phik>=0.11.1 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (0.12.4)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (2.32.3)
Requirement already satisfied: tqdm>=4.48.2 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (4.66.5)
Requirement already satisfied: seaborn>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from pandas-profiling) (0.13.2)
Requirement already satisfied: multimethod>=1.4 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from pandas-profiling) (1.12)
Requirement already satisfied: attrs>=19.3.0 in c:\programdata\anaconda3\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\programdata\anaconda3\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (3.3)
Requirement already satisfied: imagehash in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.1)
Requirement already satisfied: Pillow in c:\programdata\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (10.4.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2023.3)
Requirement already satisfied: annotated-types>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2025.1.31)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.48.2->pandas-profiling) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.16.0)
Requirement already satisfied: PyWavelets in c:\programdata\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.7.0)
Using cached joblib-1.1.1-py2.py3-none-any.whl (309 kB)
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.4.2
    Uninstalling joblib-1.4.2:
      Successfully uninstalled joblib-1.4.2
Successfully installed joblib-1.1.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.12.2 requires visions[type_image_path]<0.8.0,>=0.7.5, but you have visions 0.7.4 which is incompatible.
scikit-learn 1.5.1 requires joblib>=1.2.0, but you have joblib 1.1.1 which is incompatible.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
!pip install --upgrade visions

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: visions in c:\programdata\anaconda3\lib\site-packages (0.7.4)
Collecting visions
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\programdata\anaconda3\lib\site-packages (from visions) (1.26.4)
Requirement already satisfied: pandas>=2.0.0 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from visions) (2.2.3)
Requirement already satisfied: attrs>=19.3.0 in c:\programdata\anaconda3\lib\site-packages (from visions) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\programdata\anaconda3\lib\site-packages (from visions) (3.3)
Requirement already satisfied: multimethod>=1.4 in c:\users\pmgho\appdata\roaming\python\python312\site-packages (from visions) (1.12)
Collecting puremagic (from visions)
  Downloading puremagic-1.28-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->visions) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->visions) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->visions) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->visions) (1.16.0)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading puremagic-1.28-py3-none-any.whl (43 kB)
Installing collected packages: puremagic, visions
Successfully installed puremagic-1.28 visions-0.8.1

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/90/36/4a0d674198adabadba21eb4048df5cc2e25a4ecff38d75e974d51a83fda2/visions-0.8.1-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/90/36/4a0d674198adabadba21eb4048df5cc2e25a4ecff38d75e974d51a83fda2/visions-0.8.1-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/90/36/4a0d674198adabadba21eb4048df5cc2e25a4ecff38d75e974d51a83fda2/visions-0.8.1-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/90/36/4a0d674198adabadba21eb4048df5cc2e25a4ecff38d75e974d51a83fda2/visions-0.8.1-py3-none-any.whl.metadata
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
ydata-profiling 4.12.2 requires visions[type_image_path]<0.8.0,>=0.7.5, but you have visions 0.8.1 which is incompatible.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
from pandas_profiling import ProfileReport

C:\Users\pmgho\AppData\Local\Temp\ipykernel_19076\2274191625.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

In [20]:
import pandas as pd
from pandas_profiling import ProfileReport

# Assuming 'df' is your DataFrame
print(df.head())
print(df.info())

prof = ProfileReport(df)
prof.to_file(output_file='output.html')

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [21]:
!pip show ipywidgets

Name: ipywidgets
Version: 7.8.1
Summary: IPython HTML widgets for Jupyter
Home-page: http://ipython.org
Author: IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: C:\ProgramData\anaconda3\Lib\site-packages
Requires: comm, ipython, ipython-genutils, jupyterlab-widgets, traitlets, widgetsnbextension
Required-by: cufflinks, jupyter

In [22]:
!pip install --upgrade ipywidgets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipywidgets in c:\programdata\anaconda3\lib\site-packages (7.8.1)
Collecting ipywidgets
  Downloading ipywidgets-8.1.5-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: comm>=0.1.3 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.12 (from ipywidgets)
  Downloading widgetsnbextension-4.0.13-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.12 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.13-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.5)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Downloading ipywidgets-8.1.5-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.13-py3-none-any.whl (214 kB)
Downloading widgetsnbextension-4.0.13-py3-none-any.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   -------- ------------------------------- 0.5/2.3 MB 49.5 kB/s eta 0:00:37
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ------------- -------------------------- 0.8/2.3 MB 36.0 kB/s eta 0:00:44
   ----------------- ---------------------- 1.0/2.3 MB 49.3 kB/s eta 0:00:27
   ----------------- ---------------------- 1.0/2.3 MB 49.3 kB/s eta 0:00:27
   ----------------- ---------------------- 1.0/2.3 MB 49.3 kB/s eta 0:00:27
   ----------------- ---------------------- 1.0/2.3 MB 49.3 kB/s eta 0:00:27
   ----------------- ---------------------- 1.0/2.3 MB 49.3 kB/s eta 0:00:27
   ---------------------- ----------------- 1.3/2.3 MB 61.2 kB/s eta 0:00:17
   ---------------------- ----------------- 1.3/2.3 MB 61.2 kB/s eta 0:00:17
   -------------------------- ------------- 1.6/2.3 MB 75.2 kB/s eta 0:00:11
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ------------------------------- -------- 1.8/2.3 MB 88.4 kB/s eta 0:00:06
   ----------------------------------- ---- 2.1/2.3 MB 69.7 kB/s eta 0:00:04
   ----------------------------------- ---- 2.1/2.3 MB 69.7 kB/s eta 0:00:04
   ----------------------------------- ---- 2.1/2.3 MB 69.7 kB/s eta 0:00:04
   ---------------------------------------- 2.3/2.3 MB 77.1 kB/s eta 0:00:00
Installing collected packages: widgetsnbextension, jupyterlab-widgets, ipywidgets
Successfully installed ipywidgets-8.1.5 jupyterlab-widgets-3.0.13 widgetsnbextension-4.0.13

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
from pandas_profiling import ProfileReport
import pandas as pd
prof = ProfileReport(df, title="My Report")
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
profile=ProfileReport(tips,title='Prajwal Data')
profile.to_file(output_file='prajwaltips.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [27]:
info=ProfileReport(prajwal_data,title='Filght Data')
profile.to_file(output_file='Filght_prajwal.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [28]:
datainfo=ProfileReport(prajwal_dataset2,title='Iris_data')
profile.to_file(output_file='Iris_dataset_prajwalg.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]